name: Gate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gate
        uses: synapse-sentinel/gate@master
        with:
          coverage-threshold: 80
          coverage-directory: src
          github-token: ${{ secrets.GITHUB_TOKEN }}
